### ISSUE TITLE
Irregular test errors

### ISSUE THREAD

**Issue by mycognosist** [ssb-ngi-pointer/ssb-meta-feeds#19]
Test failures occasionally occur during CI runs. I have not yet encountered these errors while testing on my machine.

Here's an [example failure](https://github.com/ssb-ngi-pointer/ssb-meta-feeds/pull/18/checks?check_run_id=3277963806) for the validation PR.

```shell
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined

    at Function.from (buffer.js:330:9)
    at /home/runner/work/ssb-meta-feeds/ssb-meta-feeds/query.js:57:34
```

It seems that the `getSeed()` query ([L57 in `query.js`](https://github.com/ssb-ngi-pointer/ssb-meta-feeds/blob/master/query.js#L57)) is being passed an `undefined` value:

`const seedBuf = Buffer.from(msg.value.content.seed, 'hex')`

The `getSeed()` function is called from [L119 of `test/query.js`](https://github.com/ssb-ngi-pointer/ssb-meta-feeds/blob/master/test/query.js#L119).

**Comment by mycognosist** [comment]
I'm not going to spend too much time on this right now; just wanted to document so I can move on.

**Comment by staltz** [comment]
Yep! I came here to report this bug, and it's the same bug. More details:

I console.logged `msg.value.content` and it turns out it's a private message, i.e. a string suffixed with `.box`. I think maybe ssb-db2 hasn't had the time (is it a race condition?) to decrypt `msg.value.content`, which is (in the case of seeds) always a private message to yourself.

cc @arj03 who is the box1 expert in ssb-db2.

**Comment by arj03** [comment]
Ohh, I'll add that to my list
