### ISSUE TITLE
Error: Invalid feed format: ssb:feed/gabbygrove-v1/...

### ISSUE THREAD

**Issue by cryptix** [ssb-ngi-pointer/ssb-meta-feeds#53]
I can't make sense of this yet but after adding index-feed-writer and updating to ssb-meta-feeds@0.24.0 and ssb-db2@2.6.0 in my go-ssb tests, this error turned into an uncaught throw:

```
/home/cryptix/go-repos/ssb/tests/js-db2/node_modules/ssb-meta-feeds/feeds-lookup.js:86
      throw new Error('Invalid feed format: ' + feedId)
      ^

Error: Invalid feed format: ssb:feed/gabbygrove-v1/_8oxp8Aha2abfPPrMZHxB14A5fIcjOyJaf-s-uOGN6Y=
    at detectFeedFormat (/home/cryptix/go-repos/ssb/tests/js-db2/node_modules/ssb-meta-feeds/feeds-lookup.js:86:13)
    at msgToDetails (/home/cryptix/go-repos/ssb/tests/js-db2/node_modules/ssb-meta-feeds/feeds-lookup.js:93:26)
    at updateLookup (/home/cryptix/go-repos/ssb/tests/js-db2/node_modules/ssb-meta-feeds/feeds-lookup.js:139:21)
    at /home/cryptix/go-repos/ssb/tests/js-db2/node_modules/pull-stream/sinks/drain.js:24:37
    at /home/cryptix/go-repos/ssb/tests/js-db2/node_modules/pull-stream/throughs/filter.js:17:11
    at /home/cryptix/go-repos/ssb/tests/js-db2/node_modules/pull-stream/throughs/flatten.js:28:16
    at /home/cryptix/go-repos/ssb/tests/js-db2/node_modules/pull-stream/throughs/map.js:19:9
    at /home/cryptix/go-repos/ssb/tests/js-db2/node_modules/pull-stream/throughs/through.js:19:9
    at /home/cryptix/go-repos/ssb/tests/js-db2/node_modules/pull-stream/throughs/filter.js:17:11
    at /home/cryptix/go-repos/ssb/tests/js-db2/node_modules/pull-stream/throughs/flatten.js:28:16
```

https://github.com/ssb-ngi-pointer/ssb-meta-feeds/blob/f9df35f8bfbc283e8f39d75249ee9e3e13a87fa8/feeds-lookup.js#L86

**Comment by cryptix** [comment]
This happens from my code adding a GabbyGrove feed as a subfeed, not opening an ebt stream.

**Comment by staltz** [comment]
`detectFeedFormat` is new code in ssb-meta-feeds 0.24.0. I think a solution is to just detect gabby grove feed IDs as well. So just an `else if (isGabbyGroveV1FeedSSBURI(feedId))`

**Comment by cryptix** [comment]
I maybe should add that this crashed my node processes.

I'd advise to not throw an error like that when somebody else experiments with new formats... 😅

**Comment by staltz** [comment]
v0.25.0
